spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
      
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: 'OFF'
    org.springframework.cloud: 'OFF'